module.exports.genders = ['male', 'female', 'Abinary', 'Agender', 'Ambigender', 'Androgyne', 'Androgynous', 'Aporagender', 'Autigender', 'Bakla', 'Bigender',
    'Binary', 'Bissu', 'Butch', 'Calabai', 'Calalai', 'Cis', 'Cis female', 'Cis male', 'Cis man', 'Cis woman', 'Demi-boy', 'Demiflux',
    'Demigender', 'Demi-girl', 'Demi-guy', 'Demi-man', 'Demi-woman', 'Dual gender', 'Faʻafafine', 'Female to male', 'Femme', 'FTM',
    'Gender bender', 'Gender diverse', 'Gender gifted', 'Genderfae', 'Genderfluid', 'Genderflux', 'Genderfuck', 'Genderless', 'Gender nonconforming',
    'Genderqueer', 'Gender questioning', 'Gender variant', 'Graygender', 'Hijra', 'Intergender', 'Intersex', 'Kathoey', 'Māhū', 'Male to female',
    'Man', 'Man of trans experience', 'Maverique', 'Meta-gender', 'MTF', 'Multigender', 'Muxe', 'Neither', 'Neurogender', 'Neutrois', 'non-binary',
    'Non-binary transgender', 'Omnigender', 'Other', 'Pangender', 'Person of transgendered experience', 'Polygender', 'Sekhet', 'Third gender',
    'Trans*', 'Trans female', 'Trans male', 'Trans man', 'Trans person', 'Trans woman', 'Transgender female', 'Transgender male', 'Transgender man',
    'Transgender person', 'Transgender woman', 'Transfeminine', 'Transmasculine', 'Transsexual female', 'Transsexual male', 'Transsexual man',
    'Transsexual person', 'Transsexual woman', 'Travesti', 'Trigender', 'Tumtum', 'Two spirit', 'Vakasalewalewa', 'Waria', 'Winkte', 'Woman of trans experience',
    'X-gender', 'X-jendā', 'Xenogender'];

module.exports.roles = ['fan', 'manager', 'admin'];

module.exports.teams = ['Al Ahly', 'Zamalek SC', 'Ismaily', 'Tersana', 'Ghazl El Mahalla', 'El Mokawloon SC', 'El-Olympi', 'El Ittihad El Sakndary',
    'El-Masry', 'Haras El Hodood', 'El-Teram', 'ENPPI', 'El Mansoura SC', 'El Qanah FC', 'El Sekka El Hadid', 'Suez SC', 'El Minya FC',
    'Tanta FC', 'Aswan FC', 'El-Geish', 'Misr El Makasa', 'Smouha', 'Sharkia SC', 'Petrojet', 'El Dakhleya', 'El-Entag El-Harby', 'Wadi Degla',
    'El Gouna', 'Telephonat Bani Sweif', 'Ittihad El-Shorta', 'Damanhour', 'El Raja', 'Pyramids', 'Al Nasr', 'Nogoom', 'Petrol Asyut'];

module.exports.stadiums = ['New administrative capital stadium', 'Borg el-Arab Stadium', 'Cairo International Stadium', 'Egyptian Army Stadium',
    'Arab Contractors Stadium', '30 June Stadium', 'Al-Salam Stadium', 'Beni Ebeid Stadium', 'Ghazl el-Mahalla Stadium',
    'Cairo Military Academy Stadium', 'Suez Stadium', 'El-Sekka el-Hadid Stadium', 'Mokhtar el-Tetsh Stadium', 'Petro Sport Stadium',
    'Ismailia Stadium', 'Haras el-Hodoud Stadium', 'Port Said Stadium', 'Suez Canal Stadium', 'Alexandria Stadium', 'Bani Sweif Stadium'];

module.exports.randomMaleNames = ['Draven', 'Kareem', 'Myles', 'Emmett', 'Will', 'Jaydan', 'Fisher', 'Zaire', 'Ali', 'Isaias', 'Randall', 'Jack',
    'Yair', 'Quincy', 'Jaquan', 'Alvin', 'Cristian', 'Jakobe', 'Lincoln', 'Brogan', 'Hitler', 'stalin']

module.exports.randomDescriptions = [
    'A clash of titans',
    'A battle of wits and athleticism',
    'A symphony of skill and passion',
    'A dance of strategy and execution',
    'A rollercoaster of emotions',
    'A spectacle of teamwork and determination',
    'A display of human potential',
    'A story of triumph and heartbreak',
    'A celebration of the beautiful game',
    'A reminder of the power of sport to unite',
    'A tactical chess match on the field',
    'A test of endurance and mental fortitude',
    'A showcase of individual brilliance and collective strength',
    'A battle for bragging rights and supremacy',
    'A display of raw talent and athleticism',
    'A game of inches and split-second decisions',
    'A testament to the power of preparation and perseverance',
    'A reminder that anything is possible in sport',
    'A celebration of the spirit of competition',
    'A reminder that sport can be a powerful force for good',
    'A clash of styles and philosophies',
    'A battle for dominance and control',
    'A test of nerves and composure under pressure',
    'A display of tactical nous and tactical flexibility',
    'A game of twists and turns, keeping fans on the edge of their seats',
    'A showcase of individual flair and creativity',
    'A test of resilience and the ability to bounce back from setbacks',
    'A reminder that sport can be unpredictable and surprising',
    'A celebration of the drama and suspense of sport',
    'A reminder that sport can bring people together from all walks of life',
    'A game of moments, where one moment can change the course of the match',
    'A battle of wills and determination',
    'A test of character and the ability to overcome adversity',
    'A display of teamwork, communication, and co',
    'A spectacle of passion, dedication, and love for the game',
    'A reminder that sport can be a source of joy, excitement, and inspiration',
    'A celebration of the human spirit, resilience, and the pursuit of excellence',
    'A clash of cultures, traditions, and passions',
    'A battle for pride, honor, and the hearts of fans',
    'A testament to the power of sport to transcend borders and unite people',
    'A symphony of cheers, groans, and the rhythmic pulse of the game',
    'A tapestry of emotions, from elation to despair, woven throughout the match',
    'A display of the human capacity for both greatness and imperfection',
    'A reminder that sport is a microcosm of life, full of challenges, triumphs, and lessons',
    'A celebration of the camaraderie, shared experiences, and lasting friendships forged on the pitch',
    'A clash of ideologies, playing styles, and fan bases',
    'A battle for supremacy, where every goal, every tackle, and every save matters',
    'A display of the tactical genius of coaches, the leadership of captains, and the grit of players',
    'A rollercoaster of emotions, keeping fans on the edge of their seats, from the first whistle to the final whistle',
    'A reminder that football is not just a game, but a passion, a tradition, and a source of pride for millions around the world',
    'A symphony of skill, athleticism, and strategic brilliance',
    'A dance of passion, determination, and the pursuit of perfection',
    'A rollercoaster of ups and downs, where anything can happen in the blink of an eye',
    'A testament to the power of dreams, the courage to chase them, and the joy of achieving them',
    'A celebration of life, the beauty of sport, and the spirit of competition',
    'A clash of giants, where legends are made and legacies are forged',
    'A battle for glory, where the victors etch their names in the annals of football history',
    'A display of the resilience and perseverance of the human spirit',
    'A reminder that even in defeat, there is always something to learn and something to celebrate',
    'A celebration of the game that unites people across the globe, regardless of their background or beliefs',
    'A clash of cultures, languages, and traditions, all united by the love of the beautiful game',
    'A battle for supremacy, where teams push their limits and strive for greatness',
    'A display of the unwavering dedication and commitment of the players and coaches',
    'A rollercoaster of emotions, from the highs of scoring a goal to the lows of conceding one',
    'A reminder that football is more than just a game; it\'s a passion, a lifestyle, and a way of life',
    'A symphony of talent, teamwork, and tactical nous',
    'A dance of skill, creativity, and the ability to make the impossible possible',
    'A rollercoaster of surprises, where underdogs can rise to the occasion and topple giants',
    'A testament to the underdog spirit, the power of belief, and the beauty of defying expectations',
    'A celebration of the unpredictable nature of football, where anything can happen',
    'A clash of ideologies, where different approaches to the game collide',
    'A battle for control, where teams vie for supremacy in the midfield',
    'A display of the tactical brilliance of managers, the leadership of goalkeepers, and the grit of defenders',
    'A rollercoaster of tension, where every tackle, every clearance, and every save could decide the outcome',
    'A reminder that football is not just a sport, but a cultural phenomenon that transcends borders',
    'A symphony of passion, pride, and the unwavering belief in one\'s team',
    'A dance of determination, resilience, and the never-say-die attitude',
    'A rollercoaster of drama, where late goals and penalty shootouts can decide the fate of the match',
    'A testament to the human capacity for overcoming obstacles and achieving greatness',
    'A celebration of the beauty of sport, where passion, skill, and teamwork come together in a spectacle of human endeavor',
    'A clash of styles, where attacking flair meets defensive grit',
    'A battle for possession, where the team that controls the ball holds the key to victory',
    'A display of the tactical nous of managers, who orchestrate the game with intricate brilliance',
    'A rollercoaster of excitement, where the crowd\'s roars echo through the stadium',
    'A reminder that football is a game for everyone, from the diehard fans to the casual spectators',
    'A symphony of colors, where the vibrant jerseys and flags of the fans paint the stadium a dazzling spectacle',
    'A dance of movement, where players weave their magic on the pitch, captivating the imaginations of fans',
    'A rollercoaster of emotions, where the highs of victory are savored and the lows of defeat are overcome',
    'A testament to the power of sport to bring people together, regardless of their differences',
    'A celebration of the spirit of competition, where teams push each other to the limits',
    'A clash of cultures, where traditions and customs intertwine to create a unique atmosphere',
    'A battle for pride, where teams fight for the honor of representing their city, their country, or their club',
    'A display of the unwavering dedication and passion of the fans, who are the lifeblood of the game',
    'A rollercoaster of drama, where every match is a story waiting to be told',
    'A reminder that football is more than just a game; it\'s a passion, a tradition, and a way of life',
    'A symphony of hope, where dreams are ignited and aspirations are pursued',
    'A dance of imagination, where players create moments of magic that will be etched in football folklore',
    'A rollercoaster of surprises, where the unexpected happens, and the impossible becomes possible',
    'A testament to the human capacity to rise above adversity and achieve great things',
    'A celebration of the beautiful game, where the world comes together to witness the pinnacle of human sporting endeavor'
]